config/routes.rb
Rails.application.routes.draw do
  resources :wikis

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  get '/charges', to: 'charges#destroy', as: :downgrade

  devise_for :users

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaborators
  has_many :wikis, through: :collaborators
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         after_initialize { self.role ||= :standard }
         enum role: [:standard, :admin, :premium]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :wikis, through: :collaborators

  after_initialize { self.private ||= false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!, except: [:new]

	def new
		@stripe_btn_data = {
			key:         "#{ Rails.configuration.stripe[:publishable_key] }",
			description: "Blocipedia Membership - #{current_user.name}",
			amount:      1500
		}
	end

	def create
		@amount = 1500

		customer = Stripe::Customer.create(
			email: current_user.email,
			card:  params[:stripeToken]
		)

		charge = Stripe::Charge.create(
			customer:    customer.id,
			amount:      1500,
      description: "Blocipedia Membership - #{current_user.email}",
			currency:    'usd'
		)

		current_user.premium!

		flash[:notice] = "Thanks for upgrading to premium, #{current_user.email}!"
		redirect_to root_path

	rescue Stripe::CardError => e
		flash[:alert] = e.message
		redirect_to new_charge_path
	end

  def destroy
    current_user.standard!

    flash[:notice] = "You're account is now standard and all of your private Wiki's are now public!"
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :get_current_wiki

  def index
    @users = User.all
  end

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "New collaborator added."
    else
      flash[:alert] = "Error occured. Collaborator not added."
    end

    redirect_to :back
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:alert] = "Collaborator has been reomved!"
    else
      flash[:alert] = "Error occured. Collaborator could not be removed."
    end

    redirect_to :back
  end

  private

  def get_current_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!, except: [:index, :show]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])

  end

  def new
    @wiki = Wiki.new
    
  end

  def create
    @wiki = Wiki.new(wiki_params)

    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    @get_wikis = Collaborator.where(wiki_id: @wiki.id)
    @collaborators = User.where(id: @get_wikis.pluck(:user_id))
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the Wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfuly."
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting the post"
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:         true,
      hard_wrap:           true,
      link_attributes:     { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks:  true
    }

    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_controller_helper.rb
module ChargesControllerHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def is_user_collaborator?(id, collaborators)
    collaborators.find { |user| user[:id] == id }
  end
end

app/views/charges/_downgrade.html.erb
<%= link_to "Downgrade Account", downgrade_path, data: { confirm: "All of your private wiki's will be made public if you continue." }, :class => 'btn btn-danger btn-sm' %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

<%= render partial: 'downgrade' %>

app/views/collaborators/_form.html.erb
<div class="modal fade collaborator-modal-lg" id="collaboratorsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Manage Collaborators</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <table class="table">
            <tr>
              <th>User Name</th>
              <th>User Email</th>
              <th>Collaborator</th>
            </tr>
            <% @users.each do |user| %>
                <% if user.id != @wiki.user_id %>
                    <tr>
                      <td><%= user.name %></td>
                      <td><%= user.email %>
                      <td>
                        <% if is_user_collaborator?(user.id, @collaborators) %>
                            <%= link_to "Remove", wiki_collaborator_path(@wiki.id, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
                        <% else %>
                            <%= link_to "Add", wiki_collaborators_path(@wiki.id, user_id: user.id), method: :post, class: 'btn btn-success' %>
                        <% end %>
                      </td>
                    </tr>
                <% end %>
            <% end %>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: "all" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
      <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>Blocipedia</h1>
    <h3>Your go to blog spot!</h3>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <% if !user_signed_in? %>
        <% link_to "Sign_up", new_user_registration_path, :class => 'btn btn-primary' %>
      <% end %>
      <div class="row">
        <div class="col-sm-6">
          <% if !current_user || current_user.standard? %>
            <%= link_to "Go Premium!", new_charge_path, :class => 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki name" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki description" %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private, id: 'private' %> Private
          <% end %>
        </div>
    <% end %>
    
    <% if @wiki.private? && current_user.admin? || current_user.id == @wiki.user_id %>
        <%= render partial: 'collaborators/form', locals: { f: f } %>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".collaborator-modal-lg">
          Manage Collaborators
        </button>
    <% end %>
    <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki %>
    </h4>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit wiki: <%= @wiki.title %></h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines</p>
    <ul>
      <li>Be as descriptive as possible</li>
      <li>Make sure to format the information input</li>
      <li>Markdown language is supported</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-12">
    <div class="row">
      <div class="col-6">
        <h1>Wikis</h1>
      </div>
      <div class="col-6">
        <%= link_to "New Wiki", new_wiki_path, class: "btn btn-success float-right" if policy(:wiki).new? %>
      </div>
    </div>
    <%= render @wikis %>
  </div>
</div>
  </div>

app/views/wikis/new.html.erb
<h1>New Wiki post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines</p>
    <ul>
      <li>Be as descritpive as possible</li>
      <li>Make sure to format the information input</li>
      <li>Markdown language is supported</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %>  <small class="text-muted">  <%= @wiki.user.name %></small></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Post", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>